[project]
name = "jatan-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.8",
    "dacl10k",
    "dataset-tools",
    "kaggle>=1.6",
    "loguru>=0.7",
    "pandas",
    "python-dotenv>=1.0",
    "scikit-learn",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "transformers>=4.57.0",
    "tqdm>=4.66",
    "trl>=0.14",
    "datasets>=2.0",
    "peft>=0.12",
    "openai>=1.0",
    "Pillow>=10.0",
    "wandb>=0.25.0",
]

[tool.uv.sources]
dacl10k = { git = "https://github.com/phiyodr/dacl10k-toolkit.git" }
